### PR TITLE
checkout-ui-extensions version `0.27.0` (pre-publish)

### PR DESCRIPTION
**Pull request by jamesvidler**
### Background

This brings over the latest from `checkout-web`. This will be the last version of `checkout-ui-extensions`, before we move to the unified `ui-extensions` package. It will be matched with our corresponding, first, stable `2023-04` version. This does not need to be the absolute final publish of this package. We will likely do another patch publish within the next week or so to include some other changes before versioning is enforced. 

Preview the [generated docs](https://shopify-dev.last-checkout-ui-extensions-publish.james-vidler.us.spin.dev/docs/api/checkout-ui-extensions) (will be published in a separate PR, after this merges to `main`).

> **Note**: the preview of the docs includes both an `unstable` and a `2023-04` version which are the same right now.

### Solution
Followed the steps in [releasing libraries](https://vault.shopify.io/page/Extension-Libraries~gkKh.md).

There were follow-up commits made in this PR to bring in last minute changes from the following PRs:
- https://github.com/Shopify/checkout-web/pull/22782
- https://github.com/Shopify/checkout-web/pull/22588
- https://github.com/Shopify/checkout-web/pull/22693
- This [PR](https://github.com/Shopify/checkout-web/pull/22736) for `confirmationNumber` was applied, then [reverted](https://github.com/Shopify/checkout-web/pull/22800/)

### 🎩
Tophat changes by copying the packages from Spin into a real [scaffolded app / extension](https://shopify.dev/docs/api/checkout-ui-extensions#scaffolding-extension). 

Change into the app directory on your local machine and run this:
```
VM=direct.$(spin show -o fqdn)
rsync -av --delete $VM:~/src/github.com/Shopify/ui-extensions/packages/checkout-ui-extensions node_modules/@shopify/ && \
   rsync -av --delete $VM:~/src/github.com/Shopify/ui-extensions/packages/checkout-ui-extensions-react node_modules/@shopify/
```

You can tophat the [generated docs](https://shopify-dev.last-checkout-ui-extensions-publish.james-vidler.us.spin.dev/docs/api/checkout-ui-extensions) on this spin instance.
### Checklist

- [x] I have :tophat:'d these changes
- [x] I have updated relevant documentation

### CODE REVIEW

**Comment by jamesvidler** [comment]
There are two PRs that we are going to wait for to include these changes:
- https://github.com/Shopify/checkout-web/pull/22588
- https://github.com/Shopify/checkout-web/pull/22736 (optional)

**Comment by jamesvidler** [comment]
> @jamesvidler I have a change coming up that would be great if we can include as well:
> 
> #1041

Included! 👍

**Review by oliverigor — APPROVED** [review]
gtg from my tophatting :D

**Review by rcaplanshopify — COMMENTED** [review]
Code LGTM!

**Pull request merged**
